name: Release

on:
  push:
    tags:
      - '*'

env:
  # update with the name of the main binary and itch.io information
  binary: test-game
  itch_target: billygoatdev/test-game


jobs:

  release-web:
    runs-on: ubuntu-latest

    steps:
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: get_version
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev
      - name: Install trunk
        uses: jetli/trunk-action@v0.1.0
        with:
          version: latest
      - name: Build Release
        run: |
          trunk build --release
        # Trunk cannot import assets from relative paths (see e.g. https://github.com/thedodd/trunk/issues/395)
        # On sites like itch.io, we don't know on which base path the game gets served, so we need to rewrite all links to be relative
      - name: Make paths relative
        run: |
          sed -i 's/\/index/.\/index/g' dist/index.html
          sed -i 's/\/${{ env.binary }}/.\/${{ env.binary }}/g' dist/index.html
      - name: Zip release
        uses: vimtor/action-zip@v1
        with:
          files: dist/
          dest: ${{ env.binary }}.zip
      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.binary }}.zip
          name: web

  upload-to-itch:
    runs-on: ubuntu-latest
    needs:
      - release-web

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./builds

      - name: Install butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: get_version
      - name: Upload to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
        run: |
          for channel in $(ls builds); do
            ./butler push \
                --fix-permissions \
                --userversion="${{ steps.get_version.outputs.tag }}" \
                builds/$channel/* \
                ${{ env.itch_target }}:$channel
          done